
// download the paste json as code extension

// create empty typescript file
// copy the json data from swagger
// Ctrl + Shift + P => shortcut in VS code for aearching all the preferences
// // Generated by https://quicktype.io

export interface MovieCard {
    id: number;
    title: string;
    posterUrl: string;
    releaseDate: string;
}
